image: tico/docker

variables:
  TARGET_PATH: /root/app
  SENTRY_WEBHOOK: https://github.com/getsentry/sentry/issues/2367 #Replace it with your webhook, can be found in sentry project -> releases page

cache:
  paths:
    - .php_cs.cache
    - app/vendor

services:
  - docker:dind

stages:
  - test
  - build
  - deploy

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

.up: &up
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker-compose run update
    - docker-compose up -d
    - sleep 30
    - docker-compose exec -T app phinx migrate || true
    - docker-compose exec -T app phinx seed:run || true

.deploy: &deploy
  script:
    - cibu prepare-ssh
    - cibu compose login gitlab-ci-token $CI_JOB_TOKEN $CI_REGISTRY
    - sed -i "s/RELEASE_PLACEHOLDER/${SENTRY_RELEASE}/g" env/$CI_ENVIRONMENT_SLUG.yml
    - ssh $TARGET_HOST mkdir -p $TARGET_PATH
    - scp env/$CI_ENVIRONMENT_SLUG.yml $TARGET_HOST:$TARGET_PATH/docker-compose.yml
    - cibu compose pull
    - cibu compose update app
    - cibu compose up -d --no-deps --no-recreate
    - cibu compose cleanup
    - cibu sentry release $SENTRY_RELEASE $CI_PROJECT_URL/pipelines/$CI_PIPELINE_ID

.tags: &tags
  tags:
    - docker


codestyle:
  stage: test
  script:
    - php-cs-fixer fix --dry-run --diff
  <<: *tags

security:
  stage: test
  script:
    - security-checker security:check composer.lock
  <<: *tags

unused dependencies:
  stage: test
  script:
    - docker-compose run update
    - unused-scanner unused.php --silent
  <<: *tags

phpunit:
  stage: test
  <<: *up
  script:
    - docker-compose run phpunit
  artifacts:
    name: "phpunit"
    paths:
      - app/tests/coverage/
  <<: *tags

#codeception:
  #stage: test
  #<<: *up
  #script:
    #- docker-compose run codeception run --html report.html
  #artifacts:
    #name: "codeception"
    #paths:
      #- app/tests/_output/
  #<<: *tags

build:
  stage: build
  only:
    - master
  script:
    - docker-compose run update
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  <<: *tags

deploy:
  stage: deploy
  only:
    - master
  environment:
    name: prod
    url: https://example.com
  variables:
    TARGET_HOST: root@example.com
    SENTRY_RELEASE: $CI_ENVIRONMENT_SLUG-$CI_PIPELINE_ID
  <<: *deploy
  <<: *tags
